# Generated by Django 6.0.5 on 2026-05-29 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('MADERA', 'Madera'), ('HERRAMIENTA', 'Herramienta'), ('CONSUMIBLE', 'Consumible'), ('REPUESTO', 'Repuesto'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidad_medida', models.CharField(default='unidad', max_length=20)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='inventario.material')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
