# Generated by Django 6.0.5 on 2026-06-03 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('reservas', '0002_alter_ordentrabajo_options_alter_reserva_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumomaterial',
            options={'ordering': ['-fecha'], 'verbose_name': 'Consumo de material', 'verbose_name_plural': 'Consumos de materiales'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['nombre'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AddField(
            model_name='consumomaterial',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, help_text='Orden de trabajo a la que se asocia este consumo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos_material', to='reservas.ordentrabajo'),
        ),
        migrations.AddField(
            model_name='consumomaterial',
            name='realizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='proveedor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='material',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nivel mínimo — el sistema genera alerta cuando se alcanza', max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento'), ('PRODUCCION', 'Producción'), ('AMBOS', 'Ambos (Mantenimiento y Producción)')], help_text='Clasificación según uso: mantenimiento, producción o ambos', max_length=20),
        ),
    ]
