# Generated by Django 6.0.5 on 2026-05-29 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorTPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('disponibilidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rendimiento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oee', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_tpm', to='maquinas.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='InspeccionTPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('limpieza', models.BooleanField(default=True)),
                ('lubricacion', models.BooleanField(default=True)),
                ('ajuste', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('OK', 'Correcto'), ('OBSERVACION', 'Con Observaciones'), ('CRITICO', 'Crítico')], default='OK', max_length=20)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones_tpm', to='maquinas.maquina')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HallazgoTPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=20)),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='tpm.inspecciontpm')),
            ],
        ),
    ]
