# Generated by Django 6.0.5 on 2026-06-03 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0002_alter_maquina_options_alter_pieza_options_and_more'),
        ('tpm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicadortpm',
            name='maquina',
        ),
        migrations.RemoveField(
            model_name='inspecciontpm',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='inspecciontpm',
            name='maquina',
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MANTENIMIENTO_PROXIMO', 'Mantenimiento próximo'), ('MANTENIMIENTO_VENCIDO', 'Mantenimiento vencido'), ('STOCK_BAJO', 'Stock de material bajo'), ('INSPECCION_FALLIDA', 'Inspección diaria fallida'), ('CERTIFICACION_POR_VENCER', 'Certificación por vencer'), ('CERTIFICACION_VENCIDA', 'Certificación vencida'), ('INCIDENTE', 'Incidente / condición de riesgo'), ('PARADA_NO_PLANIFICADA', 'Parada no planificada registrada')], max_length=30)),
                ('severidad', models.CharField(choices=[('INFO', 'Informativa'), ('ADVERTENCIA', 'Advertencia'), ('CRITICA', 'Crítica')], default='ADVERTENCIA', max_length=15)),
                ('referencia_id', models.PositiveIntegerField(blank=True, help_text='ID del objeto origen (Mantenimiento, Material, Incidente, etc.)', null=True)),
                ('referencia_tipo', models.CharField(blank=True, help_text="Nombre del modelo origen: 'Mantenimiento', 'Material', 'Incidente'...", max_length=50)),
                ('mensaje', models.TextField(help_text='Descripción legible de la alerta para mostrar al usuario')),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
                ('vista_en', models.DateTimeField(blank=True, null=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('maquina', models.ForeignKey(blank=True, help_text='Máquina relacionada con la alerta (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='maquinas.maquina')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL)),
                ('vista_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_vistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-generada_en'],
            },
        ),
        migrations.CreateModel(
            name='CertificacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_otorgamiento', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones', to='maquinas.maquina')),
                ('otorgado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificaciones_otorgadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificación de usuario',
                'verbose_name_plural': 'Certificaciones de usuarios',
                'ordering': ['-fecha_vencimiento'],
                'unique_together': {('usuario', 'maquina', 'fecha_otorgamiento')},
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CASI_ACCIDENTE', 'Casi accidente'), ('CONDICION_RIESGO', 'Condición de riesgo'), ('ACCIDENTE', 'Accidente'), ('ANOMALIA', 'Anomalía operacional')], max_length=20)),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10)),
                ('descripcion', models.TextField()),
                ('accion_tomada', models.TextField(blank=True)),
                ('requiere_mantenimiento', models.BooleanField(default=False, help_text='Si True → genera una Alerta automáticamente al ingeniero')),
                ('fecha_ocurrencia', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='maquinas.maquina')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_reportados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-fecha_ocurrencia'],
            },
        ),
        migrations.CreateModel(
            name='InspeccionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nivel_aceite_ok', models.BooleanField(default=True, verbose_name='Nivel de aceite lubricación OK')),
                ('presion_neumatica_ok', models.BooleanField(default=True, verbose_name='Presión neumática dentro del rango (5–7 bar)')),
                ('nivel_refrigerante_ok', models.BooleanField(default=True, verbose_name='Nivel de refrigerante OK')),
                ('limpieza_area_ok', models.BooleanField(default=True, verbose_name='Área de trabajo limpia (virutas, refrigerante)')),
                ('ruidos_anormales', models.BooleanField(default=False, verbose_name='¿Se detectaron ruidos anormales?')),
                ('vibraciones_anormales', models.BooleanField(default=False, verbose_name='¿Se detectaron vibraciones anormales?')),
                ('temperatura_normal', models.BooleanField(default=True, verbose_name='Temperatura de operación normal')),
                ('guardas_seguridad_ok', models.BooleanField(default=True, verbose_name='Guardas y protecciones de seguridad en su lugar')),
                ('boton_emergencia_ok', models.BooleanField(default=True, verbose_name='Botón de parada de emergencia operativo')),
                ('observaciones', models.TextField(blank=True)),
                ('aprobada', models.BooleanField(default=True, help_text='False si algún ítem crítico falla — bloquea la máquina ese día')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones_diarias', to='maquinas.maquina')),
            ],
            options={
                'verbose_name': 'Inspección diaria',
                'verbose_name_plural': 'Inspecciones diarias',
                'ordering': ['-fecha'],
                'unique_together': {('maquina', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='HallazgoInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10)),
                ('resuelto', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='tpm.inspecciondiaria')),
            ],
            options={
                'verbose_name': 'Hallazgo de inspección',
                'verbose_name_plural': 'Hallazgos de inspección',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroOEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveSmallIntegerField()),
                ('disponibilidad', models.DecimalField(decimal_places=2, help_text='A = Tiempo real / Tiempo de carga × 100', max_digits=5)),
                ('rendimiento', models.DecimalField(decimal_places=2, help_text='P = Unidades reales / Unidades esperadas × 100', max_digits=5)),
                ('calidad', models.DecimalField(decimal_places=2, help_text='Q = Unidades sin defecto / Total unidades × 100', max_digits=5)),
                ('oee', models.DecimalField(decimal_places=2, editable=False, help_text='OEE = (A × P × Q) / 10000', max_digits=5)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_oee', to='maquinas.maquina')),
            ],
            options={
                'verbose_name': 'Registro OEE',
                'verbose_name_plural': 'Registros OEE',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('maquina', 'mes', 'anio')},
            },
        ),
        migrations.DeleteModel(
            name='HallazgoTPM',
        ),
        migrations.DeleteModel(
            name='IndicadorTPM',
        ),
        migrations.DeleteModel(
            name='InspeccionTPM',
        ),
    ]
