# Generated by Django 6.0.6 on 2026-06-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0002_remove_indicadortpm_maquina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacionusuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inspecciondiaria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registrooee',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
