# Generated by Django 6.0.6 on 2026-06-17 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0003_certificacionusuario_activo_incidente_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspecciondiaria',
            name='nivel_aceite_ok',
        ),
        migrations.RemoveField(
            model_name='inspecciondiaria',
            name='nivel_refrigerante_ok',
        ),
        migrations.RemoveField(
            model_name='inspecciondiaria',
            name='presion_neumatica_ok',
        ),
        migrations.AlterField(
            model_name='inspecciondiaria',
            name='aprobada',
            field=models.BooleanField(default=True, help_text='False si algún ítem crítico (fijo o del catálogo) falla — bloquea la máquina ese día'),
        ),
        migrations.AlterField(
            model_name='inspecciondiaria',
            name='limpieza_area_ok',
            field=models.BooleanField(default=True, verbose_name='Área de trabajo limpia'),
        ),
        migrations.CreateModel(
            name='ItemChecklistInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(help_text='Ej: OPTIMUM — el ítem aplica a todas las máquinas de este fabricante+modelo', max_length=100)),
                ('modelo_maquina', models.CharField(help_text='Ej: F210HSC', max_length=100)),
                ('nombre', models.CharField(help_text="Texto que verá el operario, ej: 'Presión neumática dentro del rango (5–7 bar)'", max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Detalle adicional o criterio de aceptación (opcional)')),
                ('es_critico', models.BooleanField(default=True, help_text='Si falla, la inspección completa queda como no aprobada')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición en el checklist')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ítem de checklist',
                'verbose_name_plural': 'Ítems de checklist',
                'ordering': ['fabricante', 'modelo_maquina', 'orden', 'nombre'],
                'unique_together': {('fabricante', 'modelo_maquina', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaChecklistInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_checklist', to='tpm.inspecciondiaria')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='tpm.itemchecklistinspeccion')),
            ],
            options={
                'verbose_name': 'Respuesta de checklist',
                'verbose_name_plural': 'Respuestas de checklist',
                'ordering': ['item__orden', 'item__nombre'],
                'unique_together': {('inspeccion', 'item')},
            },
        ),
    ]
