# Generated by Django 6.0.6 on 2026-06-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0004_remove_inspecciondiaria_nivel_aceite_ok_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemchecklistinspeccion',
            name='fabricante',
            field=models.CharField(help_text='Nombre del fabricante — el ítem aplica a todas las máquinas de este fabricante+modelo', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemchecklistinspeccion',
            name='modelo_maquina',
            field=models.CharField(help_text='Modelo de la máquina', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemchecklistinspeccion',
            name='nombre',
            field=models.CharField(help_text='Texto que verá el operario, incluyendo el criterio concreto del fabricante', max_length=200),
        ),
    ]
