# Generated by Django 6.0.6 on 2026-06-23 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0006_alter_certificacionusuario_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificacionusuario',
            name='otorgado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificaciones_otorgadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificacionusuario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='reportado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_reportados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspecciondiaria',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
