# Generated by Django 6.0.6 on 2026-06-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0007_alter_certificacionusuario_otorgado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('MANTENIMIENTO_PROXIMO', 'Mantenimiento próximo'), ('MANTENIMIENTO_VENCIDO', 'Mantenimiento vencido'), ('STOCK_BAJO', 'Stock de material bajo'), ('INSPECCION_FALLIDA', 'Inspección diaria fallida'), ('CERTIFICACION_POR_VENCER', 'Certificación por vencer'), ('CERTIFICACION_VENCIDA', 'Certificación vencida'), ('INCIDENTE', 'Incidente / condición de riesgo'), ('PARADA_NO_PLANIFICADA', 'Parada no planificada registrada'), ('BITACORA_ATENCION', 'Bitácora de operario requiere atención')], max_length=30),
        ),
    ]
