# Generated by Django 6.0.6 on 2026-07-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0009_add_asignado_nota_resolucion_alerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('MANTENIMIENTO_PROXIMO', 'Mantenimiento próximo'), ('MANTENIMIENTO_VENCIDO', 'Mantenimiento vencido'), ('STOCK_BAJO', 'Stock de material bajo'), ('INSPECCION_FALLIDA', 'Inspección diaria fallida'), ('CERTIFICACION_POR_VENCER', 'Certificación por vencer'), ('CERTIFICACION_VENCIDA', 'Certificación vencida'), ('INCIDENTE', 'Incidente / condición de riesgo'), ('PARADA_NO_PLANIFICADA', 'Parada no planificada registrada'), ('BITACORA_ATENCION', 'Bitácora de operario requiere atención'), ('RESERVA_AFECTADA_MANTENIMIENTO', 'Reserva afectada por mantenimiento')], max_length=30),
        ),
    ]
