# Generated by Django 6.0.5 on 2026-05-27 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(max_length=200)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('OPERATIVA', 'Operativa'), ('MANTENIMIENTO', 'Mantenimiento'), ('FUERA_SERVICIO', 'Fuera de servicio')], default='OPERATIVA', max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='maquinas/')),
                ('manual_pdf', models.FileField(blank=True, null=True, upload_to='manuales/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('ubicacion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='piezas/')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='maquinas.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinas.pieza')),
            ],
        ),
    ]
