# Generated by Django 6.0.5 on 2026-06-03 18:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquina',
            options={'ordering': ['nombre'], 'verbose_name': 'Máquina', 'verbose_name_plural': 'Máquinas'},
        ),
        migrations.AlterModelOptions(
            name='pieza',
            options={'ordering': ['maquina', 'ensamble', 'numero_posicion', 'nombre'], 'verbose_name': 'Pieza', 'verbose_name_plural': 'Piezas'},
        ),
        migrations.AlterModelOptions(
            name='transferenciapieza',
            options={'ordering': ['-fecha'], 'verbose_name': 'Transferencia de pieza', 'verbose_name_plural': 'Transferencias de piezas'},
        ),
        migrations.RemoveField(
            model_name='pieza',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='pieza',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='pieza',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='pieza',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='transferenciapieza',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='transferenciapieza',
            name='origen',
        ),
        migrations.AddField(
            model_name='maquina',
            name='alto_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='ancho_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='anio_fabricacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='capacidad_refrigerante_l',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad del tanque de refrigerante en litros', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='codigo_barras_universidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maquina',
            name='frecuencia_hz',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Frecuencia de red en Hz (ej. 50)', null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='largo_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='presion_neumatica_max_bar',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Presión neumática máxima de operación en bar', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='presion_neumatica_min_bar',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Presión neumática mínima de operación en bar', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas_a_cargo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maquina',
            name='rpm_husillo_max',
            field=models.PositiveIntegerField(blank=True, help_text='RPM máximo del husillo principal', null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tipo_control_cnc',
            field=models.CharField(blank=True, help_text='Ej: Siemens Sinumerik 828D', max_length=100),
        ),
        migrations.AddField(
            model_name='maquina',
            name='voltaje_v',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tensión de alimentación en voltios (ej. 400)', null=True),
        ),
        migrations.AddField(
            model_name='pieza',
            name='cantidad_en_maquina',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Cantidad de esta pieza instalada en la máquina (Qty del manual)', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pieza',
            name='ensamble',
            field=models.ForeignKey(blank=True, help_text='Ensamble padre (Baugruppe). Dejar vacío si esta pieza ES el ensamble.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piezas_hijas', to='maquinas.pieza'),
        ),
        migrations.AddField(
            model_name='pieza',
            name='es_ensamble',
            field=models.BooleanField(default=False, help_text='Marcar si esta entrada representa un Baugruppe (subconjunto), no una pieza individual'),
        ),
        migrations.AddField(
            model_name='pieza',
            name='especificacion',
            field=models.CharField(blank=True, help_text='Talla o especificación técnica (ej: M8xP1.25x20L, 30TAC62BSUC10PN7B)', max_length=200),
        ),
        migrations.AddField(
            model_name='pieza',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pieza',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pieza',
            name='imagen_pieza',
            field=models.ImageField(blank=True, null=True, upload_to='piezas/fotos/'),
        ),
        migrations.AddField(
            model_name='pieza',
            name='imagen_ubicacion',
            field=models.ImageField(blank=True, help_text='Imagen de referencia mostrando la ubicación en la máquina', null=True, upload_to='piezas/ubicacion/'),
        ),
        migrations.AddField(
            model_name='pieza',
            name='nombre_en',
            field=models.CharField(blank=True, help_text='Nombre en inglés según el manual (ej: Ballscrew)', max_length=150),
        ),
        migrations.AddField(
            model_name='pieza',
            name='nombre_original',
            field=models.CharField(blank=True, help_text='Nombre en el idioma del manual del fabricante (ej: Kugelgewindetrieb)', max_length=150),
        ),
        migrations.AddField(
            model_name='pieza',
            name='numero_parte',
            field=models.CharField(blank=True, help_text='Artikelnummer del fabricante (ej: 035112320103) — necesario para pedir repuestos', max_length=50),
        ),
        migrations.AddField(
            model_name='pieza',
            name='numero_posicion',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de posición en el diagrama del manual (Pos.)', null=True),
        ),
        migrations.AddField(
            model_name='pieza',
            name='stock_minimo_repuestos',
            field=models.PositiveIntegerField(default=0, help_text='Alerta cuando el stock baje de este valor'),
        ),
        migrations.AddField(
            model_name='pieza',
            name='stock_repuestos',
            field=models.PositiveIntegerField(default=0, help_text='Unidades de repuesto disponibles en bodega'),
        ),
        migrations.AddField(
            model_name='pieza',
            name='ubicacion_en_maquina',
            field=models.CharField(blank=True, help_text='Descripción textual de dónde está físicamente en la máquina', max_length=200),
        ),
        migrations.AddField(
            model_name='transferenciapieza',
            name='autorizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferenciapieza',
            name='maquina_destino',
            field=models.ForeignKey(blank=True, help_text='Máquina a la que se instala la pieza', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='maquinas.maquina'),
        ),
        migrations.AddField(
            model_name='transferenciapieza',
            name='maquina_origen',
            field=models.ForeignKey(blank=True, help_text='Máquina de la que se retira la pieza', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origen', to='maquinas.maquina'),
        ),
        migrations.AddField(
            model_name='transferenciapieza',
            name='motivo',
            field=models.TextField(blank=True, default='', help_text='Razón de la transferencia'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='nombre',
            field=models.CharField(help_text='Nombre en español / nombre operativo', max_length=150),
        ),
        migrations.AlterField(
            model_name='transferenciapieza',
            name='pieza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='maquinas.pieza'),
        ),
        migrations.CreateModel(
            name='CodigoParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(help_text='Ej: OPTIMUM', max_length=100)),
                ('modelo_maquina', models.CharField(help_text='Ej: F210HSC — aplica a todas las máquinas de este modelo', max_length=100)),
                ('codigo', models.CharField(help_text='Ej: PP01, PNP-M01', max_length=20)),
                ('tipo', models.CharField(choices=[('PLANIFICADA', 'Planificada (PP)'), ('NO_PLANIFICADA', 'No planificada (PNP)')], max_length=20)),
                ('categoria', models.CharField(choices=[('MECANICA', 'Mecánica'), ('ELECTRICA', 'Eléctrica'), ('NEUMATICA', 'Neumática'), ('LUBRICACION', 'Lubricación'), ('REFRIGERACION', 'Refrigeración'), ('CONTROL_CNC', 'Control CNC / Programación'), ('SEGURIDAD', 'Seguridad'), ('OPERACION', 'Operación / Setup'), ('OTRO', 'Otro')], max_length=30)),
                ('subsistema', models.CharField(help_text='Ej: Husillo / Spindle (Inline Motor)', max_length=200)),
                ('causa_raiz_comun', models.TextField(blank=True, help_text='Descripción técnica de la causa raíz más frecuente')),
            ],
            options={
                'verbose_name': 'Código de parada',
                'verbose_name_plural': 'Códigos de parada',
                'ordering': ['fabricante', 'modelo_maquina', 'tipo', 'codigo'],
                'unique_together': {('fabricante', 'modelo_maquina', 'codigo')},
            },
        ),
    ]
