# Generated by Django 6.0.6 on 2026-06-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0002_alter_maquina_options_alter_pieza_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pieza',
            options={'ordering': ['maquina', 'numero_posicion', 'nombre'], 'verbose_name': 'Pieza', 'verbose_name_plural': 'Piezas'},
        ),
    ]
