# Generated by Django 6.0.6 on 2026-06-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0003_alter_pieza_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
