# Generated by Django 6.0.6 on 2026-06-17 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0004_pieza_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoparada',
            name='fabricante',
            field=models.CharField(help_text='Nombre del fabricante de la máquina', max_length=100),
        ),
        migrations.AlterField(
            model_name='codigoparada',
            name='modelo_maquina',
            field=models.CharField(help_text='Modelo de la máquina — el código aplica a todas las máquinas de este fabricante+modelo', max_length=100),
        ),
        migrations.AlterField(
            model_name='codigoparada',
            name='subsistema',
            field=models.CharField(help_text='Subsistema o componente afectado, ej: Motor principal, Sistema de transmisión', max_length=200),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='tipo_control_cnc',
            field=models.CharField(blank=True, help_text='Tipo de controlador CNC, si aplica', max_length=100),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='ensamble',
            field=models.ForeignKey(blank=True, help_text='Ensamble padre. Dejar vacío si esta pieza ES el ensamble.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piezas_hijas', to='maquinas.pieza'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='es_ensamble',
            field=models.BooleanField(default=False, help_text='Marcar si esta entrada representa un subconjunto (ensamble), no una pieza individual'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='nombre_en',
            field=models.CharField(blank=True, help_text='Nombre en inglés según el manual del fabricante', max_length=150),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='nombre_original',
            field=models.CharField(blank=True, help_text='Nombre en el idioma del manual del fabricante, si es distinto del español', max_length=150),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='numero_parte',
            field=models.CharField(blank=True, help_text='Código o número de parte del fabricante — necesario para pedir repuestos', max_length=50),
        ),
    ]
