# Generated by Django 6.0.6 on 2026-06-29 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0006_alter_transferenciapieza_autorizado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasignacionPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ensamble_anterior', models.ForeignKey(blank=True, help_text='Ensamble del que salió la pieza (None = era pieza suelta)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasignaciones_salida', to='maquinas.pieza')),
                ('ensamble_nuevo', models.ForeignKey(blank=True, help_text='Ensamble al que se asignó (None = quedó suelta)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasignaciones_entrada', to='maquinas.pieza')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasignaciones', to='maquinas.pieza')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reasignación de pieza',
                'verbose_name_plural': 'Reasignaciones de piezas',
                'ordering': ['-fecha'],
            },
        ),
    ]
