# Generated by Django 6.0.6 on 2026-06-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0007_reasignacionpieza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='estado',
            field=models.CharField(choices=[('OPERATIVA', 'Operativa'), ('MANTENIMIENTO', 'Mantenimiento'), ('BAJA', 'Dada de baja')], default='OPERATIVA', max_length=30),
        ),
    ]
