# Generated by Django 6.0.6 on 2026-06-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0008_rename_fuera_servicio_a_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='horas_acumuladas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horas de operación acumuladas desde registros de OT cerradas', max_digits=10),
        ),
    ]
