# Generated by Django 6.0.5 on 2026-06-03 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportegenerado',
            options={'ordering': ['-fecha_generacion'], 'verbose_name': 'Reporte generado', 'verbose_name_plural': 'Reportes generados'},
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo Excel generado', null=True, upload_to='reportes/'),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='fecha_fin_periodo',
            field=models.DateField(blank=True, help_text='Fin del período analizado', null=True),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='fecha_inicio_periodo',
            field=models.DateField(blank=True, help_text='Inicio del período analizado', null=True),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='generado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='tipo',
            field=models.CharField(choices=[('INVENTARIO', 'Inventario de materiales'), ('MANTENIMIENTO', 'Mantenimiento'), ('RESERVAS', 'Reservas y órdenes de trabajo'), ('TPM_OEE', 'TPM — OEE por máquina'), ('TPM_PARETO', 'TPM — Análisis Pareto de paradas'), ('TPM_INSPECCIONES', 'TPM — Inspecciones diarias'), ('PIEZAS', 'Piezas y transferencias')], max_length=30),
        ),
    ]
