# Generated by Django 6.0.6 on 2026-07-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_reportegenerado_generado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportegenerado',
            name='tipo',
            field=models.CharField(choices=[('INVENTARIO', 'Inventario de materiales'), ('MANTENIMIENTO', 'Mantenimiento'), ('RESERVAS', 'Reservas y órdenes de trabajo'), ('TPM_OEE', 'TPM — OEE por máquina'), ('TPM_PARETO', 'TPM — Análisis Pareto de paradas'), ('TPM_INSPECCIONES', 'TPM — Inspecciones diarias'), ('PIEZAS', 'Piezas y transferencias'), ('ORDENES_MANTENIMIENTO', 'Órdenes de mantenimiento'), ('ALERTAS', 'Historial de alertas'), ('CERTIFICACIONES', 'Certificaciones de usuarios'), ('INCIDENTES', 'Incidentes y condiciones de riesgo'), ('BITACORAS', 'Bitácoras (operarios y mantenimiento)'), ('CONSUMO_MATERIALES', 'Consumo de materiales'), ('RESUMEN', 'Resumen ejecutivo')], max_length=30),
        ),
    ]
