# Generated by Django 6.0.5 on 2026-05-29 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['-fecha_programada'], 'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='horas_trabajo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='proxima_fecha',
            field=models.DateField(blank=True, help_text='Próxima fecha programada de mantenimiento', null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to=settings.AUTH_USER_MODEL),
        ),
    ]
