# Generated by Django 6.0.5 on 2026-06-03 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_alter_mantenimiento_options_and_more'),
        ('maquinas', '0002_alter_maquina_options_alter_pieza_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='descripcion',
            field=models.TextField(help_text='Qué se va a hacer / qué se hizo'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='proxima_fecha',
            field=models.DateField(blank=True, help_text='Se calcula automáticamente al finalizar según el plan asociado', null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(help_text='Descripción breve de la tarea (ej: Lubricación guías lineales)', max_length=200)),
                ('descripcion_detallada', models.TextField(blank=True, help_text='Procedimiento paso a paso según el manual del fabricante')),
                ('tipo_tpm', models.CharField(choices=[('P1_AUTONOMO', 'Pilar 1 — Autónomo (operador)'), ('P2_PREVENTIVO', 'Pilar 2 — Preventivo planificado'), ('P3_MEJORA', 'Pilar 3 — Mejora enfocada'), ('P7_SEGURIDAD', 'Pilar 7 — Seguridad')], default='P2_PREVENTIVO', max_length=20)),
                ('intervalo_valor', models.PositiveIntegerField(help_text='Número de unidades entre cada mantenimiento (ej: 500)')),
                ('intervalo_unidad', models.CharField(choices=[('HORAS', 'Horas de operación'), ('DIAS', 'Días calendario'), ('SEMANAS', 'Semanas'), ('MESES', 'Meses')], default='HORAS', max_length=10)),
                ('activo', models.BooleanField(default=True, help_text='Desactivar si la tarea ya no aplica a esta máquina')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_mantenimiento', to='maquinas.maquina')),
            ],
            options={
                'verbose_name': 'Plan de mantenimiento',
                'verbose_name_plural': 'Planes de mantenimiento',
                'ordering': ['maquina', 'intervalo_valor'],
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Plan que originó este mantenimiento (vacío en correctivos no planificados)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejecuciones', to='mantenimiento.planmantenimiento'),
        ),
    ]
