# Generated by Django 6.0.6 on 2026-06-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_alter_mantenimiento_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
