# Generated by Django 6.0.6 on 2026-06-16 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_mantenimiento_activo'),
        ('maquinas', '0004_pieza_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo')], default='PREVENTIVO', max_length=20)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_PROCESO', 'En proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20)),
                ('titulo', models.CharField(help_text='Descripción breve de lo que se debe hacer', max_length=200)),
                ('descripcion_tarea', models.TextField(blank=True, help_text='Procedimiento detallado, pasos a seguir')),
                ('fecha_programada', models.DateField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_estimado_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('repuestos_necesarios', models.TextField(blank=True, help_text='Lista de repuestos y materiales necesarios')),
                ('acciones_realizadas', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('afecta_seguridad', models.BooleanField(default=False, help_text='La falla o tarea representa un riesgo de seguridad')),
                ('para_produccion', models.BooleanField(default=False, help_text='La máquina queda fuera de servicio durante la intervención')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Visto bueno / Autorizado por')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_mantenimiento', to='maquinas.maquina')),
                ('plan', models.ForeignKey(blank=True, help_text='Plan que originó esta orden (vacío en correctivos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='mantenimiento.planmantenimiento')),
                ('responsable_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_responsable_1', to=settings.AUTH_USER_MODEL, verbose_name='Responsable principal')),
                ('responsable_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_responsable_2', to=settings.AUTH_USER_MODEL, verbose_name='Responsable 2')),
                ('responsable_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='om_responsable_3', to=settings.AUTH_USER_MODEL, verbose_name='Responsable 3')),
            ],
            options={
                'verbose_name': 'Orden de mantenimiento',
                'verbose_name_plural': 'Órdenes de mantenimiento',
                'ordering': ['-fecha_programada', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(help_text='Qué se realizó: trabajo ejecutado, hallazgos, resultados')),
                ('observaciones', models.TextField(blank=True)),
                ('repuestos_utilizados', models.TextField(blank=True, help_text='Repuestos y materiales que se usaron efectivamente')),
                ('requiere_atencion', models.BooleanField(default=False, help_text='Marcar si el ingeniero debe revisar algo urgente')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='bitacora_mantenimiento/')),
                ('maquina', models.ForeignKey(help_text='La máquina a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_mantenimiento', to='maquinas.maquina')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_mantenimiento', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(blank=True, help_text='Orden de trabajo asociada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_bitacora', to='mantenimiento.ordenmantenimiento')),
            ],
            options={
                'verbose_name': 'Entrada de bitácora',
                'verbose_name_plural': 'Bitácora de mantenimiento',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
