# Generated by Django 6.0.6 on 2026-06-16 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_ordenmantenimiento_bitacoramantenimiento'),
        ('tpm', '0003_certificacionusuario_activo_incidente_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='incidente',
            field=models.ForeignKey(blank=True, help_text='Incidente que originó esta orden (correctivos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_generadas', to='tpm.incidente'),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Plan que originó esta orden (preventivos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='mantenimiento.planmantenimiento'),
        ),
    ]
