# Generated by Django 6.0.6 on 2026-06-16 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0006_ordenmantenimiento_incidente_and_more'),
        ('reservas', '0003_ordentrabajo_activo_registroparada_activo'),
        ('tpm', '0003_certificacionusuario_activo_incidente_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='hallazgo',
            field=models.ForeignKey(blank=True, help_text='Hallazgo de inspección autónoma (Pilar 1 TPM) que originó esta orden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_generadas', to='tpm.hallazgoinspeccion'),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='inspeccion',
            field=models.ForeignKey(blank=True, help_text='Inspección diaria reprobada que originó esta orden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_generadas', to='tpm.inspecciondiaria'),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='origen',
            field=models.CharField(choices=[('MANUAL', 'Creación manual'), ('INCIDENTE', 'Incidente'), ('PLAN', 'Plan de mantenimiento'), ('INSPECCION', 'Inspección diaria reprobada'), ('HALLAZGO', 'Hallazgo de inspección autónoma'), ('PARADA', 'Parada no planificada'), ('ESTADO_MAQUINA', 'Cambio de estado de máquina')], default='MANUAL', help_text='Disparador que generó esta orden', max_length=20),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='parada',
            field=models.ForeignKey(blank=True, help_text='Parada no planificada que originó esta orden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_generadas', to='reservas.registroparada'),
        ),
    ]
