# Generated by Django 6.0.6 on 2026-06-23 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0008_alter_bitacoramantenimiento_tecnico_and_more'),
        ('reservas', '0005_alter_bitacoraoperario_operario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='bitacora_operario',
            field=models.ForeignKey(blank=True, help_text="Entrada de bitácora de operario marcada como 'requiere atención' que originó esta orden", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_generadas', to='reservas.bitacoraoperario'),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='origen',
            field=models.CharField(choices=[('MANUAL', 'Creación manual'), ('INCIDENTE', 'Incidente'), ('PLAN', 'Plan de mantenimiento'), ('INSPECCION', 'Inspección diaria reprobada'), ('HALLAZGO', 'Hallazgo de inspección autónoma'), ('PARADA', 'Parada no planificada'), ('ESTADO_MAQUINA', 'Cambio de estado de máquina'), ('BITACORA', 'Bitácora de operario — requiere atención')], default='MANUAL', help_text='Disparador que generó esta orden', max_length=20),
        ),
    ]
