# Generated by Django 6.0.6 on 2026-06-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0009_ordenmantenimiento_bitacora_operario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planmantenimiento',
            options={'ordering': ['maquina', 'nombre_tarea'], 'verbose_name': 'Plan de mantenimiento', 'verbose_name_plural': 'Planes de mantenimiento'},
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='intervalo_unidad',
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='intervalo_valor',
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='intervalo_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Cada X días calendario (ej: 30). Deja vacío para omitir este disparador.', null=True),
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='intervalo_horas',
            field=models.PositiveIntegerField(blank=True, help_text='Cada X horas de operación (ej: 500). Deja vacío para omitir este disparador.', null=True),
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='ultima_ejecucion_fecha',
            field=models.DateField(blank=True, help_text='Punto de inicio del contador de días. Actualizado automáticamente al generar una OM.', null=True),
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='ultima_ejecucion_horas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas acumuladas de la máquina en la última ejecución. Actualizado automáticamente.', max_digits=10, null=True),
        ),
    ]
