# Generated by Django 6.0.6 on 2026-06-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0010_rediseno_planmantenimiento_disparadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoramantenimiento',
            name='tiempo_horas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horas empleadas en esta actividad', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bitacoramantenimiento',
            name='tipo_actividad',
            field=models.CharField(blank=True, choices=[('DIAGNOSTICO', 'Diagnóstico / Inspección'), ('DESMONTAJE', 'Desmontaje'), ('LIMPIEZA', 'Limpieza'), ('LUBRICACION', 'Lubricación'), ('AJUSTE', 'Ajuste / Calibración'), ('REEMPLAZO', 'Reemplazo de pieza'), ('MONTAJE', 'Montaje / Ensamble'), ('PRUEBA', 'Prueba / Verificación'), ('OTRO', 'Otro')], help_text='Tipo de actividad realizada en esta entrada', max_length=20),
        ),
    ]
