# Generated by Django 6.0.5 on 2026-06-03 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0002_alter_maquina_options_alter_pieza_options_and_more'),
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Orden de trabajo', 'verbose_name_plural': 'Órdenes de trabajo'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha', '-hora_inicio'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='tiempo_estimado_horas',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='tiempo_real_horas',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='resultado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tiempo_parada_min',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tiempo total de paradas no planificadas en minutos', max_digits=7),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tiempo_planificado_min',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tiempo de carga / planificado en minutos', max_digits=7),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tiempo_real_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo real de operación en minutos', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='unidades_esperadas',
            field=models.PositiveIntegerField(default=0, help_text='Producción teórica esperada'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='unidades_producidas',
            field=models.PositiveIntegerField(default=0, help_text='Para cálculo de Rendimiento OEE'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='unidades_sin_defecto',
            field=models.PositiveIntegerField(default=0, help_text='Unidades aprobadas (para cálculo de Calidad OEE)'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='autorizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='proposito',
            field=models.CharField(choices=[('ENSENANZA', 'Enseñanza / Clase'), ('INVESTIGACION', 'Investigación / Tesis'), ('PRODUCCION', 'Producción'), ('PEDIDO_EXTERNO', 'Pedido externo')], default='ENSENANZA', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('EN_USO', 'En uso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='BitacoraOperario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('descripcion_trabajo', models.TextField(help_text='Qué se realizó en esta entrada')),
                ('observaciones', models.TextField(blank=True)),
                ('requiere_atencion', models.BooleanField(default=False, help_text='Marcar si hay algo que el ingeniero debe revisar')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='bitacora/')),
                ('operario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_bitacora', to=settings.AUTH_USER_MODEL)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_bitacora', to='reservas.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Entrada de bitácora',
                'verbose_name_plural': 'Bitácora del operario',
                'ordering': ['orden_trabajo', 'fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='RegistroParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('duracion_minutos', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('descripcion_tecnica', models.TextField(help_text='Descripción técnica / observaciones del operario sobre la parada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('codigo_parada', models.ForeignKey(blank=True, help_text='Código del catálogo del modelo de máquina', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='maquinas.codigoparada')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='reservas.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Registro de parada',
                'verbose_name_plural': 'Registros de paradas',
                'ordering': ['orden_trabajo', 'hora_inicio'],
            },
        ),
    ]
