# Generated by Django 6.0.6 on 2026-06-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_ordentrabajo_options_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registroparada',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
