# Generated by Django 6.0.6 on 2026-07-01 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_bitacoraoperario_operario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='operador',
            field=models.ForeignKey(blank=True, help_text='Operador certificado que maneja la máquina (obligatorio si el solicitante es estudiante; admin/técnico operan sus propias reservas).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_operadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
